# Generated by Django 6.0.5 on 2026-05-21 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=150)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("internship", "Internship"),
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                ("role", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("required_skills", models.TextField(blank=True)),
                ("min_batch_year", models.PositiveIntegerField(default=2024)),
                ("max_batch_year", models.PositiveIntegerField(default=2027)),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("fresher", "Fresher"),
                            ("0-1", "0-1 years"),
                            ("1-2", "1-2 years"),
                            ("2+", "2+ years"),
                        ],
                        default="fresher",
                        max_length=10,
                    ),
                ),
                ("salary", models.CharField(blank=True, max_length=80)),
                ("deadline", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posted_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("shortlisted", "Shortlisted"),
                            ("rejected", "Rejected"),
                            ("accepted", "Accepted"),
                        ],
                        default="applied",
                        max_length=20,
                    ),
                ),
                ("cover_note", models.TextField(blank=True)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "job")},
            },
        ),
        migrations.CreateModel(
            name="SavedJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by",
                        to="jobs.job",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "job")},
            },
        ),
    ]
