# Generated by Django 6.0.5 on 2026-05-21 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "branch",
                    models.CharField(
                        choices=[
                            ("CSE", "Computer Science"),
                            ("IT", "Information Technology"),
                            ("ECE", "Electronics & Communication"),
                            ("EEE", "Electrical & Electronics"),
                            ("ME", "Mechanical"),
                            ("CE", "Civil"),
                            ("Other", "Other"),
                        ],
                        default="CSE",
                        max_length=20,
                    ),
                ),
                ("batch_year", models.PositiveIntegerField(default=2026)),
                (
                    "skills",
                    models.TextField(blank=True, help_text="Comma-separated skills"),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("fresher", "Fresher"),
                            ("0-1", "0-1 years"),
                            ("1-2", "1-2 years"),
                            ("2+", "2+ years"),
                        ],
                        default="fresher",
                        max_length=10,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=15)),
                (
                    "resume",
                    models.FileField(blank=True, null=True, upload_to="resumes/"),
                ),
                ("is_placement_admin", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
